version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7-node
    steps:
      - checkout
      - run:
        name: cd src
        command: |
          cd src

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
