version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7-node
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
