version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            cd src
            gem install bundler -v 2.1.4
            bundle config --local set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
