version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7
    working_directory: ~/rails_docker/src
    steps:
      - checkout:
          path: ~/rails_docker
      - ruby/install-deps

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:migrate

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
